# Generated by Django 5.2.3 on 2025-07-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sale_session_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('call_time', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
