# Generated by Django 5.2.3 on 2025-07-08 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GoogleMapDataApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_assistant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_availability', models.JSONField(blank=True, null=True)),
                ('customer_google_business', models.ForeignKey(blank=True, db_column='customer_google_business', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='GoogleMapDataApp.googlemapmodel', to_field='shop_id_company')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sale_session_id', models.IntegerField()),
                ('call_time', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='SaleSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('close_time', models.DateTimeField(null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sale_sessions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='sale_sessions', to='HistoryApp.customermodel')),
            ],
            options={
                'db_table': 'sale_sessions',
            },
        ),
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='HistoryApp.salesessionmodel')),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.AddField(
            model_name='salesessionmodel',
            name='stage',
            field=models.ForeignKey(db_column='stage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_sessions', to='HistoryApp.stagemodel'),
        ),
    ]
