# Generated by Django 5.2.3 on 2025-07-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HistoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='customer_email',
            new_name='customer_assistan_phone',
        ),
    ]
