# Generated by Django 5.2.3 on 2025-07-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HistoryApp', '0002_rename_customer_email_customermodel_customer_assistan_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='customer_assistan_phone',
            new_name='customer_assistant_phone',
        ),
    ]
