# Generated by Django 5.2.3 on 2025-06-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMapModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('shop_id_company', models.CharField(max_length=128, unique=True)),
                ('shop_url_company', models.CharField(blank=True, max_length=512, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=128, null=True)),
                ('longitude', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('plus_code', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=1024, null=True)),
                ('search_txt', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('is_open_now', models.BooleanField(blank=True, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('provider_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('providers', models.JSONField(blank=True, null=True)),
                ('services', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'googlemaps',
            },
        ),
    ]
